### PR TITLE
Add native Node.js ES Modules support

### LINKED ISSUE #62: Exporting as ES Module Syntax (ESM)
Please, export `"module"` entry point in the `package.json` as ES Module Syntax (ESM).

More info about it here: https://www.pikapkg.com/about/

### PR DESCRIPTION
**Pull request by abdonrd**
In this PR I add **native Node.js ES Modules support**.

Following the same recommendations as the Rollup plugins:
- https://github.com/rollup/plugins/pull/413
- https://github.com/rollup/plugins/pull/419

Fix #62.

Also fix https://github.com/apollographql/apollo-client/issues/5961.

### CODE REVIEW

**Comment by Splaktar** [comment]
This would be great! Thank you @abdonrd for putting in the work on the PR.

**Comment by icco** [comment]
I would love to see this merged in!

**Comment by abdonrd** [comment]
Closing because no response.

**Comment by thescientist13** [comment]
sharing comments here from a similar thread for those following along
https://github.com/zenparsing/zen-observable/pull/69#issuecomment-878425621

**Pull request closed without merging**
